sudo: false
language: node_js
node_js:
- node
install: npm install
script:
- npm test
- gulp
cache:
  directories:
  - node_modules
deploy:
    provider: heroku
    api_key:
      secure: QFTVB5vo6/ek7LeJgQADHpG//iY61fRBDT91TUpH1SgtbHm9iHxWUgXkpjLEFAp+UcyMIJRsQojxYvLp6ztUTLvr9gceo7W5T+Ef/Pz9Vt7hHvS8uZBmMe0WCV8+d1qwGAJL02tci6vXi20hmX+P4jcu47O2jlFWLotyG0r5yRmvsCMuPLHuufKkAb7zoH9+qXRuCb/5rFBZPxEyjG6wRGK/f/ONiCgao0gTrfZ2jDSzjTzCUqgQuWkmLExt494CIrKKMhhiF8y5XnuGRf+Zvu2Nh4zS/NE56o0JwFv/gebF8L0a6e4mX0Om4ANUtyzvlDXb4eBQHtHrX0V0I7czOVjMS1r0edRC9QAOl0LYdH0zGwKRD29jDw1pnctporCcShLiKONprhsQqjLGs2STDLHe4ZsOURU1+GPTdQ2YvQQLYcXpFZ/egLAiu9B+ZmmIoUfFfZwXWaOrzfJgbywX4O9bWgZAJLr2HzWdSFiAPbpChla2FWSzc4rF0GfyFakPLspfegEo/rDkx7sAtUMJ/cZ1lLXbFy/ebsPDF9BKof+HeYgheSCFGHC0DWQAdlmh33lvDuQa6IiA8vGRLWtQkuLDe0B9BXVjrpbA/SemLwfseFe1q+r7ZaR4+wkTkEtugrYpXbtowDF+DLzdqRCFCmLt1MsThYriGs4Q4Q9/36s=
    app: BearCallMastering
    on:
      repo: splnlss/BearCallMastering
env:
  global:
  - secure: ayD4RSr9mFIdo74AcXIJguvpLH8+fMGYfovWDalStc1C7eXXWuwfA3XRxbzFPhnuFg50c3D9vkEjY2yiaoKKJUyQb+ake8SJefcSHYTpu+HesiqG24ZyHFypHBvlFQQ9wDeE9glfaJn8IzE+yedvhIH//ouWlR1+1RZQlIlPyceor9txepahuKiehNtnj7xnmMRgWgT+iGq6k2QDE7gvZOvgqK6jtktxJM6YqxrETUB01elgfk2F6JU+rMQKDnmPzmwsuSjPihxzOufAusXslYn1CC92Qj9Dr48mxz1m+uBFFhNIvc65Irjf7gbEQInYTTZaFepfBcBciX3IlPbHUVck359p/PkAgWTvnkd6VEaHYx+2KVQc3l0EwYi0Qh5zydnvhwuCx7XfIWW4B73bYqo52I7b0evvoM0OXx3i36XLVZ+aLrdVnrRToGkjp6ILQYik0eQIdx9Z9To4GzY1x6zoXVMwdK1PfGxGEweMacYYuXe7Rez2V1Fa8xWFiArhYryCMDB8Lx0LLL2UHskS24TFuGLtUY/jLMgd2ErTQrEeXUuc+07nuvbyQ66DT8LyjugRmWgzoB7yudSZI+/lzo5AsQurjSLS9TdZO6lue0DNGnVeXuZ88x1P52QA+6ucfJNkpQQjrqPp0hdpX6G5BbFfxn7QG/RyHpZq4zFFr5g=
  - secure: cbly+L4W6kJgzQW8ReRWurxO9RCgSJ7/VggypJQUyAjkKsEAeR6R5H6CmwQN8BVy/h+Hhi3VXtMggp9/GvqIG9e62RclK/ZSoSoRh74d+XS7bC15dAOUHP+ilqo2JXGaISZP/3l6U3SpFBMlTCmG6y0MmsWmlQ98l6ctJ4HvAGiNm1scRC5u6y+FkvmRRsE4U6eTaTe+4zBBondtrUaljMPky1gqxTkdFYJry8DquYEj/KCuoLT+wbcRkpKrld/TBUYD/ypKdhw+UtMQ808OmrHwA8Xsd2m9gFA8vDdVaR2CM3fRt/Q0vjjImV6xz/MvdvGS3SBfBBq/IjaoxF0BlA0xn8EbE5HrqdfDA+bMN6hmi+emgzQRbU9qpwyx6Nvr50Om+K2PGeOhJrxwUEkxEebi5yClX5w8MCF5YehTJLrDEC4V1fOgD/55QnzcWYltDHJHoLCvgjp1HsWIuqJQhsBcXA3NUcAt9e7nXQAh7qgPqr8PJYc0c28DidEbVN49NtxgmtyiZTqRJX1jWpbnalACtYWyuJ6TnWFEti9qC5TyM8uUMwCDpnOyO9p0OEKGU9p+0Na6AfI2pEUcGmv/nUIz/90DVUjWLiPv5S5ZhipFGq0Fw2FTZoHMyZ0QDRS3iFoBgIApGfGZI7iGPJweYEMaMNVGRZv/RTer8kflqac=
