sudo: false
language: node_js
node_js:
- node
install: npm install
script:
- npm test
- gulp
cache:
  directories:
  - node_modules
deploy:
  provider: heroku
  api_key:
    secure: QFTVB5vo6/ek7LeJgQADHpG//iY61fRBDT91TUpH1SgtbHm9iHxWUgXkpjLEFAp+UcyMIJRsQojxYvLp6ztUTLvr9gceo7W5T+Ef/Pz9Vt7hHvS8uZBmMe0WCV8+d1qwGAJL02tci6vXi20hmX+P4jcu47O2jlFWLotyG0r5yRmvsCMuPLHuufKkAb7zoH9+qXRuCb/5rFBZPxEyjG6wRGK/f/ONiCgao0gTrfZ2jDSzjTzCUqgQuWkmLExt494CIrKKMhhiF8y5XnuGRf+Zvu2Nh4zS/NE56o0JwFv/gebF8L0a6e4mX0Om4ANUtyzvlDXb4eBQHtHrX0V0I7czOVjMS1r0edRC9QAOl0LYdH0zGwKRD29jDw1pnctporCcShLiKONprhsQqjLGs2STDLHe4ZsOURU1+GPTdQ2YvQQLYcXpFZ/egLAiu9B+ZmmIoUfFfZwXWaOrzfJgbywX4O9bWgZAJLr2HzWdSFiAPbpChla2FWSzc4rF0GfyFakPLspfegEo/rDkx7sAtUMJ/cZ1lLXbFy/ebsPDF9BKof+HeYgheSCFGHC0DWQAdlmh33lvDuQa6IiA8vGRLWtQkuLDe0B9BXVjrpbA/SemLwfseFe1q+r7ZaR4+wkTkEtugrYpXbtowDF+DLzdqRCFCmLt1MsThYriGs4Q4Q9/36s=
  app: BearCallMastering
  on:
    repo: splnlss/BearCallMastering
env:
  global:
    secure: CEB6Bps6OH5PJbed8R+a5UCC39Nh1bEoJFUlmk9kZgC4Pw+AlCyDjmowaU2JXCsT9o9si04VgmyngHF2eN/WhgJN2zTz/ZX+MJfcbBP4BdWgSDrD3eKFdjILYsDYMThPLE/6Z+ewrXRTUC6VDjS1RBpubyXeYqTNmMRZIT4hdbjnrMBWFAVJA2ZuX3QIyQxWTszsUAyxyGkM3ErR9/IaF9E5xg21EmPP69CCQYIqH/wVJPV1cRaiZelymZatG/3q/k12DI1pTuLdevkZ0U2RTffiY4nepKbdTIvjcMOG+lsN9dnzJOCl7g3FFAk69wvTEt2KrZ7cwhiVwgdwupEkRPI6SHYQaYr/pHq+1H5hhrZg9OcL7Ic4Ca0KpCtKzxPoUCMyTIJELdeVtoHh359x3G6b5ROtzmcozWwLq5Ogl0dTDLsrrZot3/WQcakCeF5JPooc251LSSwSAwjhfOuf/DEd3bzSZ3FN49yREJlpxyztg63sHBdApmDoTMZxtkma9J1YNQzh8xYsPKd9y66o2LAn9AUA866hyH7LMkLBsChEsLJaasamMKONybqfHY5je9eiABNCuZds1olN+v5CGiXnmeY8iIzC2wQPIPyaQChRTo7zvWaEF+gSDqsVi0X5CHHjlHW5sS23n09Fgq2QfDMGMwgwHkcwYJ9VnvhC7sE=
